=== TalaDaniel/2021_LMSGI_DACF/ud04/12.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="recetas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="tiempo">
                                <xs:complexType>
                                    <xs:attribute name="preparacion" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ingredientes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingrediente" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombreIngrediente" type="xs:string"/>
                                                    <xs:element name="cantidad" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:integer">
                                                                     <xs:attribute name="unidad" type="xs:string"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>    
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="instrucciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="paso" type="xs:string" maxOccurs="10"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="plato" type="xs:string"/>       
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TalaDaniel/2021_LMSGI_DACF/ud04/12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM '12.dtd'>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="12.xsd">
    <receta plato="primero">
        <nombre>Risotto milanesa</nombre>
        <descripcion></descripcion>
        <tiempo preparacion="40"/>
        <ingredientes>
            <ingrediente>
                <nombreIngrediente>Arroz</nombreIngrediente>
                <cantidad unidad="gramos">500</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Cebolla Mediana</nombreIngrediente>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Azafrán</nombreIngrediente>
                <cantidad unidad="pizca">1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Queso Parmesano</nombreIngrediente>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Mantequilla</nombreIngrediente>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Sal</nombreIngrediente>              
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Pimienta</nombreIngrediente>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Caldo</nombreIngrediente>
                <cantidad unidad="mililitros">1000</cantidad>
            </ingrediente>
            <ingrediente>
                <nombreIngrediente>Vino Blanco</nombreIngrediente>
                <cantidad unidad="chorro">1</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>
            <paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla</paso>
            <paso>Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca</paso>
            <paso>A continuación, incorporamos el arroz, lo sofreimos un poco</paso>
            <paso>Vamos añadiendo el caldo caliente poco a poco mientras removemos</paso>
            <paso>Salpimentamos</paso>
            <paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso</paso>
            <paso>Servimos enseguida</paso>
        </instrucciones>   
    </receta>
</recetas>
