=== TalaDaniel/2021_LMSGI_DACF/ud04/Videojuegos.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT formulario (datos,consolas+,establecimiento)>
<!ATTLIST formulario
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>

<!ELEMENT datos (nombre,direccion,email,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT consolas (nintendo,playstation,xbox)*>
<!ELEMENT nintendo EMPTY>
<!ATTLIST nintendo
    consola CDATA #REQUIRED>
<!ELEMENT playstation EMPTY>
<!ATTLIST playstation
    consola CDATA #REQUIRED>
<!ELEMENT xbox EMPTY>
<!ATTLIST xbox
    consola CDATA #REQUIRED>
<!ELEMENT establecimiento (codigoPostal,satisfaccion,tiempoTecnologia)>
<!ELEMENT codigoPostal EMPTY>
<!ATTLIST codigoPostal
    direccion CDATA #IMPLIED>
<!ELEMENT satisfaccion EMPTY>
<!ATTLIST satisfaccion
    nota CDATA #REQUIRED>
<!ELEMENT tiempoTecnologia EMPTY>
<!ELEMENT uso EMPTY>
<!ATTLIST uso
    tiempo CDATA #IMPLIED>

=== TalaDaniel/2021_LMSGI_DACF/ud04/Videojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulario SYSTEM 'Videojuegos.dtd'> 
<formulario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Videojuegos.xsd"> 
    <datos>
        <nombre>Daniel</nombre>
        <direccion>C/AvenidaConsolas</direccion>
        <email>videojuegos@gmail.com</email>
        <telefono>007691233</telefono>
    </datos>
    <consolas>
        <nintendo consola="switch"/>
        <playstation consola="ps5"/>
        <xbox consola="SerieX"/>
    </consolas>
    <establecimiento>
        <codigoPostal direccion="49600"/>
        <satisfaccion nota="9"/> 
        <tiempoTecnologia></tiempoTecnologia>
    </establecimiento>
</formulario>
